cluster:
  nodes:
    - id: node1
      address: 192.168.1.100:9001
      client_port: 8001
      data_dir: data/node1
    
    - id: node2
      address: 192.168.1.101:9002
      client_port: 8002
      data_dir: data/node2
    
    - id: node3
      address: 192.168.1.102:9003
      client_port: 8003
      data_dir: data/node3